version: '1.0'

services:
  todosDB:
    image: postgres:15.3
    container_name: mindflow-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mindflow
      - POSTGRES_PASSWORD=mindflow
    volumes:
      - ./postgres:/var/lib/postgresql/data
